# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_QWidget(object):
    def setupUi(self, QWidget):
        QWidget.setObjectName("QWidget")
        QWidget.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QWidget.sizePolicy().hasHeightForWidth())
        QWidget.setSizePolicy(sizePolicy)
        QWidget.setMinimumSize(QtCore.QSize(400, 300))
        QWidget.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        QWidget.setFont(font)
        self.label_logo = QtWidgets.QLabel(QWidget)
        self.label_logo.setGeometry(QtCore.QRect(50, 0, 300, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/pic/logo.png"))
        self.label_logo.setObjectName("label_logo")
        self.LE_usrname = QtWidgets.QLineEdit(QWidget)
        self.LE_usrname.setGeometry(QtCore.QRect(50, 150, 300, 25))
        self.LE_usrname.setMaxLength(32)
        self.LE_usrname.setObjectName("LE_usrname")
        self.LE_pwd = QtWidgets.QLineEdit(QWidget)
        self.LE_pwd.setGeometry(QtCore.QRect(50, 190, 300, 25))
        self.LE_pwd.setText("")
        self.LE_pwd.setMaxLength(32)
        self.LE_pwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.LE_pwd.setObjectName("LE_pwd")
        self.PB_signin = QtWidgets.QPushButton(QWidget)
        self.PB_signin.setGeometry(QtCore.QRect(155, 230, 90, 30))
        self.PB_signin.setObjectName("PB_signin")

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "sctf2020"))
        # self.LE_usrname.setText(_translate("QWidget", "SCTFer"))
        self.LE_usrname.setPlaceholderText(_translate("QWidget", b"user name"))
        self.LE_pwd.setPlaceholderText(_translate("QWidget", b"password"))
        self.PB_signin.setText(_translate("QWidget", "Sign In"))
